"""empty message

Revision ID: 420778e1620e
Revises: 
Create Date: 2024-02-11 14:03:06.382689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420778e1620e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Actuality', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status',
    sa.Column('status_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('status_name')
    )
    op.add_column('order', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_column('order', 'name_owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name_owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order', 'owner_id')
    op.drop_table('status')
    op.drop_table('menu')
    # ### end Alembic commands ###
