"""empty message

Revision ID: d7fb3bbbe5d9
Revises: 420778e1620e
Create Date: 2024-02-11 14:15:32.609025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fb3bbbe5d9'
down_revision = '420778e1620e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('actuality', sa.Boolean(), nullable=False))
    op.drop_column('menu', 'Actuality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('Actuality', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('menu', 'actuality')
    # ### end Alembic commands ###
